# Generated by Django 4.0.2 on 2022-02-10 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='text2',
        ),
    ]
